### ISSUE TITLE
Map Progress

### ISSUE THREAD

**Issue by felikatze** [felikatze/isat-script-project#50]
How many Map files of the game have been 100% finished!

- [x] Map001 (Test Room "FinalTemplates")
- [x] Map002 (Meadow "MEADOW")
- [x] Map003 ("ACT5_Hallway (Locked 3-3L)")
- [x] Map008 ("BossHallway_1")
- [x] Map010 ("Castle Entrance")
- [x] Map011 ("Hallway")
- [x] Map013 (Victory Room "THE END")
- [x] Map016 ("TutoMonsterHallway")
- [x] Map017 (centre room "FLOOR 1, END")
- [x] Map018 ("KingRoom")
- [x] Map019 (centre room "FLOOR 2, END")
- [x] Map020 (Last Room "LastRoom")
- [x] Map021 (Miraquest "Miraquest")
- [x] Map022 (Dormont East "Village E")
- [x] Map023 (F3 Snackbreak)
- [x] Map024 (F3 King Room)
- [x] Map025 (Odilequest "OdileQuest")
- [x] Map026 (F3 Observatory)
- [x] Map027 (centre room "FLOOR 3, END")
- [x] Map028 ("KeyRoom (Key 0-0)")
- [x] Map029 (entrance "StorageRoom")
- [x] Map030 (Dormont Center "DORMONT")
- [x] Map033 (Entrance)
- [x] Map034 (Favor Tree "Village Tree (LOOP)")
- [x] Map037 (F1 SnackBreak)
- [x] Map040 ("BossHallway_2")
- [x] Map041 (F2 Snackbreak)
- [x] Map044 ("BossHallway_3")
- [x] Map047 (f2 "Hallway (FrozenPerson)")
- [x] Map048 (f3 "Hallway (Tears)")
- [x] Map050 (F2 Gardening Room)
- [x] Map051 ("ClockTower" cutscene)
- [x] Map052 (f2 "Hallway (Locked 2-1)")
- [x] Map053 (Last Room, act6 "EPILOGUE")
- [x] Map056 ("ACT5_Castle Entrance")
- [x] Map061 ("BonnieQuest")
- [x] Map062 (Dormont Shop "Shop")
- [x] Map064 (Dormont North "Village N")
- [x] Map065 (Isaquest "IsaQuest")
- [x] Map066 (Dormont Library "Library")
- [x] Map067 ("House_FrozenWife")
- [x] Map068 ("House_Novels")
- [x] Map069 ("House_Change")
- [x] Map070 (Boulangerie "House_Boulangerie")
- [x] Map071 (f3 "Hallway (Locked 3-1)")
- [x] Map072 ("House_Flowers")
- [x] Map073 (House Cook "House_Cook")
- [x] Map074 ("House_Storage")
- [x] Map075 ("Hallway (Locked 1-1)" f1)
- [x] Map076 (floor 0 "FLOOR 1, START")
- [x] Map077 ("Armory")
- [x] Map079 ("CandleDorm (Timecraft)")
- [x] Map080 (f1 "WritingDorm (Key 1-2F)")
- [x] Map082 ("Admin (Key 2-1L)")
- [x] Map083 (f2 "Hallway" to secret library)
- [x] Map084 (F2 Library)
- [x] Map085 (F2 Secret Library)
- [x] Map086 (Death Corridor)
- [x] Map087 (f2 "Hallway (Locked 2-2)")
- [x] Map088 ("Room (Crest)" f2)
- [x] Map089 (f2 "Classroom (Key 3-3L)")
- [x] Map090 (f2 "Hallway (RowTears)")
- [x] Map091 (infirmary)
- [x] Map092 (f3 "Hallway (Locked 3-2)")
- [x] Map093 (f3 "StairstoSTARS (Tears)" hallway)
- [x] Map096 (F3 Dog Room)
- [x] Map097 ("Room (Crest)" f3)
- [x] Map098 (f3 "Hallway (Tears)")
- [x] Map099 ("MirrorRoom (Key 3-1)")
- [x] Map100 (F3 Writing Room)
- [x] Map101 ("ACT5_KeyRoom (Key 0-0)")
- [x] Map102 (F3 Miradorm)
- [x] Map103 (F2 Locked Room)
- [x] Map104 ("Changing Room (Key 3-2)")
- [x] Map105 (f3 "Hallway (Locked 3-3L)")
- [x] Map106 (f3 "HallwayToBathroom&Key")
- [x] Map107 ("Bathroom")
- [x] Map108 (F3 Hallway / Ghost Event)
- [x] Map109 (F1 Hallway / First Tears)
- [x] Map110 (tutorial "MonsterHallway")
- [x] Map111 ("BreakRoom" f1)
- [x] Map112 ("Storage Room (Locked") (Floor 1 Stostorage Roomoom)
- [x] Map113 ("Hallway (RowTears)" f1)
- [x] Map114 ("KingGate" Star-door room)
- [x] Map115 (f1 "Kitchen (Key 1-1)")
- [x] Map116 ("Room (Crest)" f1)
- [x] Map117 (f2 "TrapmakingRoom (Key 2-3F)")
- [x] Map118 (BigKeyRoom (Keyknife))
- [x] Map119 ("PotteryRoom")
- [x] Map121(GAMEOVER)
- [x] Map122 (F3 Final Hallway / Roommate)
- [x] Map123 (f2 "HallwayToLibrary")
- [x] Map124 (F1 Hallway /(LVL Difference)
- [x] Map125 ("Hallway (Ghost1)" floor 1)
- [x] Map126 (f2 "Hallway (Ghost2)")
- [x] Map127 (Loopquest "LoopQuest")
- [x] Map128 ("ChangeGodMeeting")
- [x] Map129 ("ACT5_StorageRoom")
- [x] Map130 ("FLOOR 1, END" act 5)
- [x] Map132 ("ACT5_Hallway (Locked 1-1)")
- [x] Map133 ("ACT5_Armory")
- [x] Map134 ("ACT5_Hallway (Ghost1)")
- [x] Map136 ("ACT5_CandleDorm (Timecraft)")
- [x] Map137 ("ACT5_WritingDorm (Key 1-2F)")
- [x] Map140 ("ACT5_Hallway (Tear)")
- [x] Map141 ("ACT5_BreakRoom" f1)
- [x] Map142 ("ACT5_Storage Room (Locked)" f1)
- [x] Map143 ("ACT5_Hallway (RowTears)" no non-generic text)
- [x] Map144 ("ACT5_Room (Crest)" f1)
- [x] Map145 ("ACT5_Kitchen (Key 1-1)")
- [x] Map149 (act 5 first snack "FLOOR 2, START")
- [x] Map151 (act 5 "FLOOR 2, END")
- [x] Map153 ("ACT5_Hallway (FrozenPerson)")
- [x] Map154 ("ACT5_Hallway" f2)
- [x] Map155 ("ACT5_Garden")
- [x] Map156 ("ACT5_Hallway (Locked 2-1)")
- [x] Map157 ("ACT5_Admin (Key 2-1L)")
- [x] Map158 ("ACT5_HallwayToLibrary")
- [x] Map159 ("ACT5_Library (Key 2-2)")
- [x] Map162 ("ACT5_Hallway (Ghost2)")
- [x] Map163 ("ACT5_Hallway (Locked 2-2)")
- [x] Map164 ("ACT5_Classroom (Key 3-3L)")
- [x] Map165 ("ACT5_Room (Crest)" f2)
- [x] Map166 ("ACT5_Hallway (RowTears)" f2)
- [x] Map167 ("ACT5_Infirmary")
- [x] Map168 ("ACT5_TrapmakingRoom (Key 2-3F)")
- [x] Map169 ("ACT5_BreakRoom (Locked)" f2)
- [x] Map173 (act 5 second snack "FLOOR 3, START")
- [x] Map175 (act5 centre "FLOOR 3, END")
- [x] Map177 ("ACT5_Hallway (Locked 3-1)"
- [x] Map178 ("ACT5_StairstoSTARS (Tears)")
- [x] Map179 ("Act5_Star Room")
- [x] Map180 ("ACT5_PotteryRoom")
- [x] Map181 ("ACT5_Hallway (Tears)" f3)
- [x] Map182 ("ACT5_MiraRoom")
- [x] Map183 ("Act5_Changing Room (Key 3-2)")
- [x] Map185 ("Act5_KingRoom")
- [x] Map186 ("House_Boulangerie" act6)
- [x] Map188 ("ACT5_Bathroom")
- [x] Map189 ("ACT5_HallwayToKey(Ghost3)")
- [x] Map190 (ACT5_BigKeyRoom (Keyknife))
- [x] Map193 (f3 "ACT5_Hallway (Tears)")
- [x] Map194 ("ACT5_MirrorRoom (Key 3-1)")
- [x] Map195 ("ACT5_Writing Room")
- [x] Map196 ("ACT5_Room (Crest)" f3)
- [x] Map198 ("ACT5_BreakRoom")
- [x] Map200 ("ACT5_Hallway (Roommate)")
- [x] Map202 ("THE KING" 3rd snack act 5)
- [x] Map205 (KingRoom Act5)
- [x] Map206 ("THE END" act 5)
- [x] Map207 ("Hallway" act5 post king
- [x] Map208 ("LastRoom [Battle]")
- [x] Map209 ("Hallway [NPCs]")
- [x] Map210 ("EPILOGUE")
- [x] Map211 ("Village E")
- [x] Map212 ("Village N")
- [x] Map213 (Favor Tree, act6 "Village Tree (LOOP)")
- [x] Map214 (f3 "Hallway" to the secret room)
- [x] Map216 (F3 Secret Room)

Maps that do not contain any noteworthy text:

- Map004
- Map005 ("CUTSCENES")
- Map006 ("Title")
- Map007 ("TestingStuff")
- Map009 (f2 "Hallway")
- Map012 ("CASTLE_HOUSE")
- Map014 ("VILLAGE")
- Map015
- Map031
- Map032 (pre king "Hallway")
- Map035
- Map036 ("Stairs" 1st snack->f2 centre)
- Map038
- Map039  ("Stairs" 2nd snack->f3 centre)
- Map042
- Map043
- Map045
- Map049 ("Stairs" 3rd snack->king)
- Map054 ("--------ACT 5-6")
- Map055 ("ACT5_CASTLE")
- Map057 ("ACT5_Entrance")
- Map058 ("ACT5_TutoMonsterHallway")
- Map059 ("ACT5_MonsterHallway")
- Map060 ("TEMPLATES N DEBUG")
- Map063
- Map078 (f1 "Hallway")
- Map081 ("FLOOR 1, START" act5)
- Map094 ("Hallway" midboss1->1st snack)
- Map095 (f3 "Hallway")
- Map120 ("Hallway" midboss2->2nd snack)
- Map131
- Map135 (f1 "ACT5_Hallway")
- Map138
- Map139 ("ACT5_Hallway (LVL difference)")
- Map146
- Map147 ("ACT5_BossHallway_1")
- Map148 ("ACT5_Hallway" midboss1->1st snack)
- Map150 ("ACT5_Stairs" 1st snack->f2 centre)
- Map152
- Map160 ("ACT5_Hallway" to the secret library)
- Map161
- Map170
- Map171 ("ACT5_BossHallway_2")
- Map172 ("ACT5_Hallway" btwn midboss2 and f3)
- Map174 ("ACT5_Stairs" 2nd snack->f3 centre)
- Map176
- Map184 ("Act5_KingGate")
- Map187 ("ACT5_HallwayToBathroom&Key"
- Map191
- Map192 ("ACT5_Hallway (Locked 3-2)")
- Map197 (f3 "ACT5_Hallway" to dog break room)
- Map199 ("ACT5_BossHallway_3")
- Map201
- Map203 ("Stairs" 3rd snack->king act5)
- Map204 ("Hallway" ^)
- Map215 ("ACT 6")
- Map217 ("DebugRoom")
