### ISSUE TITLE
Common Events Progress (1-199)

### ISSUE THREAD

**Issue by felikatze** [felikatze/isat-script-project#52]
Split into multiple issues because Feli crashed his browser making just one.

- [x] 47 | Item_SilverCoin

- [x] 48 | BONNIEACTION
- [x] 49 | EXAMINE
- [x] 50 | SKILL_Ask King
- [x] 51 | ITEM_Doll
- [x] 52 | ITEM_doodle

- [x] 54 | Text variables
- [x] 55 | ITEM_remindernote

- [x] 57 | ITEM_Glass
- [x] 58 | ITEM_brightflower
- [x] 59 | ITEM_earring
- [x] 60 | ITEM_poem
- [x] 61 | ITEM_starshapedleaf
- [x] 62 | BATTLE_StartBattle

- [x] 65 | ITEM_Clay

- [x] 67 | ITEM_suicide
- [x] 68 | memory of skirmish
- [x] 69 | Mirror pic
- [x] 70 | sharpening stone
- [x] 71 | Pendant
- [x] 72 | Chain
- [x] 73 | Tarot Card

- [x] 76 | GiftforMira
- [x] 77 | Cut In King
- [x] 78 | ITEM_snacks

- [x] 83 | Tears Code

- [x] 88 | MonsterDefeat

- [x] 90 | KingLose

- [x] 104 | LOOP_loopbackdialogue

- [x] 106 | GAMEOVER_Picture
- [x] 107 | GAMEOVER_Teleport

- [x] 116 | LOOP_specialdeathevent

- [x] 120 | SavePoint

- [x] 122 | TutoFightRock
- [x] 123 | TutoFightPaper
- [x] 124 | TutoFightScissors
- [x] 125 | Potionsjoke
- [x] 126 | UnlockSkills
- [x] 127 | BathroomMonologue
- [x] 128 | BathroomFriends

- [x] 130 | IsabeauDormontConvo
- [x] 131 | KingStartAttackEnd
- [x] 132 | OdileSidequest
- [x] 133 | LockedDoor
- [x] 134 | SkipFriendquest
- [x] 135 | WeaponFoundAgain

- [x] 139 | Bonnie_smells
- [x] 140 | Tuto_MessedUpType

- [x] 142 menu_sif
- [x] 144 menu_mira (handled by text variables)
- [x] 145 menu_isa
- [x] 146 menu_odile
- [x] 147 menu_bonnie
- [x] 154 menu_sifACT3
- [x] 156 menu_sifACT5
- [x] 158 menu_sifACT6
- [x] 252 menu_mira (act6)
- [x] 253 menu_isa (^)
- [x] 254 menu_odile (^)
- [x] 255 menu_bonnie (^)

- [x] 162 | PreDialogue
- [x] 163 | Chatting

- [x] 165 | WhatToDoAct2
- [x] 166 | HadAQuestion…
- [x] 167 | WhatToDo Act 3-4
- [x] 168 | CallLoop

- [x] 172 | SteppyCookingBook
- [x] 173 | RunningBook
- [x] 174 | OdileEdge
- [x] 175 | AsktheKing?

- [x] 182 | last ingredient
- [x] 183 | longthingy
- [x] 184 | shortgizmogadget
- [x] 185 | MakeBomb
- [x] 186 | UseBomb
- [x] 187 | TriedAllSnacks
- [x] 188 | ColumnsEventA
- [x] 189 | ColumnsEventB
- [x] 190 | BirdEvent
- [x] 191 | BarrelEventDormont
- [x] 192 | OdileCantGoThere
- [x] 193 | LoopInteractTuto
- [x] 194 | FlowersInteract
- [x] 195 | TorchInteract
- [x] 196 | BunchaFlowersInteract
- [x] 197 | FakeDoorDormont

**Comment by felikatze** [comment]
we did it lads
