### ISSUE TITLE
Map Progress (sasasap)

### ISSUE THREAD

**Issue by felikatze** [felikatze/isat-script-project#54]
Only mark as complete once ALL relevant text from a map is in a script somewhere!
As a side note - SASASAP uses way less common events. Generic text is applied to every single object individually. Which is insane, and I'm happy adrienne doesn't do that in isat, if only for her own sanity.

- [x] Map001 (Meadow)
- [x] Map002 (King Room WIN)
- [x] Map003 (Rest Room / Snack break)
- [x] Map005 (Longer / Hallway dark scene)
- [x] Map007 (King Room)
- [x] Map009 (template)
- [x] Map011 (Longer / Hallway "cool attack" scene)
- [x] Map013 (Longer / Hallway ghost + frozen roommate)
- [x] Map014 (Prayer Room)
- [x] Map017 (Maiden's Room)
- [x] Map018 (Key)
- [x] Map019 (Last Hallway / Candy Scene)
- [x] Map020 (IntroRoom / Intro Cutscene)
- [x] Map023 (Storage Room)
- [x] Map025 (Intro / First Room)
- [x] Map027 (Tears Room 1)
- [x] Map028 (Empty Room)
- [x] Map029 (Tears Room 2)
- [x] Map030 (Dining Room)
- [x] Map031 (Monster Room)
- [x] Map033 (Door Room)
- [x] Map034 (Library)
- [x] Map038 (Big Room)
- [x] Map039 (Writing Room)
- [x] Map040 (Kitchen)
- [x] Map041 (Infirmary)
- [x] Map042 (Hair Door)
- [x] Map044 (Bathroom)

Maps without relevant text:

- Map004
- Map006 (Longer / Hallway)
- Map007 (Longer / Hallway)
- Map010 (Longer / Hallway)
- Map012 (Longer / Hallway)
- Map015 (Longer / Hallway)
- Map016 (Longer / Text for the torches here is in Map009)
- Map021 (Longer / Hallway)
- Map022
- Map024
- Map026 (Longer / Hallway)
- Map037 (Hallway)
- Map043 (Hair Door Open)
- Map045 (contains unused dialogue though)
